// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjtxlirbyqajfpaazosy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdHhsaXJieXFhamZwYWF6b3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzA1MTMsImV4cCI6MjA2NzA0NjUxM30.4MAAy6Qd6H7ADAZsa9YP7oGERwwjyBwcHk6DiDZPFIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});